language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install pandas
  - pip install scipy
  - pip install pandas
# command to run tests
script:
  - python test/enrichmentAnalysis_test.py
